### ISSUE TITLE
friend sharing

### ISSUE THREAD

**Issue by aarondunn** [aarondunn/simpleshare#40]
How long would this take to add? If we let people add custom email addresses, and added them as "friends" in addition to the drop target? Would box send the email for us?
![screen shot 2014-05-28 at 12 18 09 pm](https://cloud.githubusercontent.com/assets/3102237/3111098/5a7ab93e-e6ad-11e3-907c-1d4e2ea7eb31.png)

**Comment by Rognarroc** [comment]
You mean share it in common way, but do not copy link to clipboard, instead  open mail app and start a new letter with email selected as recipient and link in email body?

**Comment by aarondunn** [comment]
right basically it would send a link via email. Ideally we could use Amazon ses or a mailclient or something.

**Comment by aarondunn** [comment]
@Rognarroc can you investigate this as an option to email? http://aws.amazon.com/ses/

then lets estimate total time for this feature and either start or close if its too hard

**Comment by Rognarroc** [comment]
IMHO there is no need in using such service. I can use MailCore library https://github.com/MailCore/mailcore2 to send emails from app. Of course, user have to input email account credentials for it. Please describe a  GUI in more details for this functionality.

**Comment by aarondunn** [comment]
yea thats the issue, users im sure wont want to input some email client details. So if we do that behind the scenes it would be much nicer. how long would just the GUI part take to build?




again its simple, in preferences we add something where use can add favorites list, email address + name of user. Then when user drags to icon they can drag to middle as normal target, or to the persons avatar to send them a link to the file

**Comment by Rognarroc** [comment]
When all these icons should appear? Or this is some kind of links on desktop? Persons avatar: locally assigned or avatar from box.net account?

**Comment by aarondunn** [comment]
when user drags file or folder to the mac taskbar icon




avatar can be from gravatar?

**Comment by aarondunn** [comment]
Did we ever end up estimating time required for this? I had a new idea, maybe we can use facebook login to enable the avatars and to find emails for friends?

**Comment by Rognarroc** [comment]
Facebook API is good idea and not very difficult to implement. Main challenge is to position avatars like on a picture.If we want to use all friends from Facebook, there will be a lot of avatars. Also is simply open Mail application with To field filled ok or program have to send email by itself?
