### ISSUE TITLE
Bug with screencasts when upload disable.

### ISSUE THREAD

**Issue by Rognarroc** [aarondunn/simpleshare#61]
Sometimes screencasts do not saved to desktop when uploads disabled.

**Comment by aarondunn** [comment]
@Rognarroc was this fixed in the test version you sent

**Comment by Rognarroc** [comment]
Yes, screencasts are always saved on desktop, regardless upload switch.

**Comment by aarondunn** [comment]
but it should delete the file if that option is set, correct?

**Comment by Rognarroc** [comment]
If "delete all file types after upload" option is on, app copies screencast to desktop, uploads it and deletes if upload was successful.
