### ISSUE TITLE
Create gif from video screencast?

### ISSUE THREAD

**Issue by aarondunn** [aarondunn/simpleshare#72]
Would be nice if we can easily generate gif files from screencasts as an option for users, like to share on blogs or twitter.

**Comment by aarondunn** [comment]
@Rognarroc any idea how  hard this would be? Giving users option to make a gif file vs mp4 video, so they can embed on blogs and such. Could be a nice feature

**Comment by Rognarroc** [comment]
Found a library that looks promising, will try it tomorrow. https://github.com/unixpickle/GifPro

**Comment by Rognarroc** [comment]
Resulting gif colours are bad, need to make more research, because there is a software which can capture gifs in good quality (Gif Grabber for example).

**Comment by aarondunn** [comment]
Seems this one is finished?

**Comment by Rognarroc** [comment]
As a basic feature, yes.
