### ISSUE TITLE
Gif preview bug

### ISSUE THREAD

**Issue by aarondunn** [aarondunn/simpleshare#74]
User reports seeing this in preview, I guess we should replace with the image icon for gif files:

![image](https://cloud.githubusercontent.com/assets/3102237/7094083/718e8078-df73-11e4-8dd2-79a8c90bc5ea.png)

**Comment by aarondunn** [comment]
@Rognarroc were you able to see this bug?

**Comment by Rognarroc** [comment]
Found two possibilities of this bug: when connection finishes successfully but do not provide data for thumbnail, when connection finishes with error. Fixed by using default placeholder image in both cases.

**Comment by aarondunn** [comment]
thanks
