### ISSUE TITLE
Bugs with new release...

### ISSUE THREAD

**Issue by aarondunn** [aarondunn/simpleshare#75]
There are several bugs with the latest release of simpleshare...

- [x] Screenshot is spelled wrong: 
![image](https://cloud.githubusercontent.com/assets/3102237/7291389/acb35e78-e944-11e4-94fc-4c8c2cc683d7.png)
This should be on by default and is misspelled, please put: Compress screenshot images

- [x] Icon is showing as inactive (grey) even though im logged in and its not disabled...why?
![image](https://cloud.githubusercontent.com/assets/3102237/7291401/e3511240-e944-11e4-87f2-b407b5e71d6c.png)

- [x] The images are supposed to be 2x for retina, but its small: http://i.imgur.com/K1J4wKR.png
- [x] Clicking the icon is flashing white...

**Comment by Rognarroc** [comment]
Sent you update in oDesk.  Which images are not presented in 2x quality?

**Comment by aarondunn** [comment]
when the image compression settings are turned on

**Comment by Rognarroc** [comment]
When compression is turned on, screenshots are smaller than they should be in retina?

**Comment by aarondunn** [comment]
yes it looks half the normal size of a normal retina screenshot

**Comment by Rognarroc** [comment]
I posted update at Odesk, it should fix small size after compression issue.

**Comment by Rognarroc** [comment]
FIxed.
